### ISSUE TITLE
Button looks off

### ISSUE THREAD

**Issue by NomarCub** [czottmann/obsidian-copy-search-url#3]
The button looks different from the others it's next to. It's not centered vertically, its color is stronger, and it doesn't change its background when hovered.

![image](https://user-images.githubusercontent.com/5298006/192110353-7413535e-cb38-4012-9339-954cefb6cf8b.png)

**Comment by czottmann** [comment]
@NomarCub Thanks for the bug report. Do you use the default theme or another one?

**Comment by NomarCub** [comment]
I have some snippets, but I also tested this in the sandbox vault and it's the same there.

**Comment by czottmann** [comment]
Which Obsidian version?  Are you on 0.15 or 0.16? (I've tested it against 0.15.x but my guess is that the HTML structure in 0.16 is a bit different, CSS classes and all.)

**Comment by NomarCub** [comment]
I am on 0.16.

**Comment by czottmann** [comment]
@NomarCub Fixed in 1.1, out now. Thanks for reporting it!
