### ISSUE TITLE
Links open in new Obsidian window?

### ISSUE THREAD

**Issue by nightgolfer** [czottmann/obsidian-copy-search-url#8]
When I copy a search URL via the plugin and then click it, the search launches a new instance of Obsidian (a new window) instead of just performing the search in the Obsidian window I already have open.

My link looks like this:

```
[search-term](obsidian://search?vault=my-vault&query=search-term)
```

Am I doing something wrong? Is there a way to force the link open inside the already-open Obsidian window?

**Update**: I managed to get it working by removing the vault parameter:

```
[search-term](obsidian://search?query=search-term)
```

**Comment by czottmann** [comment]
Hi @nightgolfer, this is not something that the plugin can influence, I'm afraid. Obsidian itself is responsible with handling the `obsidian://` call, and thus decides whether to open a new window or not.

In other words: At the time Copy Search URL is called by Obsidian, the app has already decided whether to open a new window or not.

Unfortunately, I don't know of any setting in the app to influence this behavior. 🤷🏻‍♂️ I suggest asking around on the official forum or Discord.
